Page({
  data:{
    selectedIndex:0,
    currentIndex:0,
    book:[
      {'text':'全部订单'},
      {'text':'未支付'},
      {'text':'待接单'},
      {'text':'正在进行'},
      {'text':'已完成'}
    ],
    take:[
      {'text':'全部订单'},
      {'text':'正在进行'},
      {'text':'已完成'}
    ],
    bookOrderList:[
      [
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        }
      ],
      [
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        }
      ]
    ],
    takedOrderList:[
      [
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        }
      ],
      [
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        },
        {
          orderId:'12',
          status:1,
          content:'dddd',
          createTime:'2020',
          amount:'12'
        }
      ]
    ]
  },
  bindBarTap:function(e){
    this.setData({
      selectedIndex: e.currentTarget.dataset.index,
      currentIndex: e.currentTarget.dataset.index
    })
  },
  bindSwiperChange:function(e){
    // 触摸更改时，更新left-tabbr选中
    if(e.detail.source == 'touch'){
      this.setData({
        selectedIndex: e.detail.current
      })
    }
  }
})